name: aplikacja_sklep
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.14.0 <3.0.0'

flutter_intl:
  enabled: true
  main_locale: pl

dependencies:
  bot_toast: 4.0.1
  cupertino_icons: 1.0.2
  dartz: 0.10.0
  dio: 4.0.0
  enum_to_string: 2.0.1
  equatable: 2.0.3
  fimber: 0.6.1
  fluro: 2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: 7.3.0
  flutter_localizations:
    sdk: flutter
  flutter_pagewise: 2.0.1
  form_validator: 1.0.0-nullsafety.1
  get_it: 7.2.0
  hive: 2.0.4
  hive_flutter: 1.1.0
  intl: 0.17.0
  json_annotation: 4.1.0
  mask_text_input_formatter: 2.0.0
  pedantic: 1.11.1
  pretty_dio_logger:
    git:
      url: https://github.com/appvinio/pretty_dio_logger.git
  shared_preferences: 2.0.8
  shimmer: 2.0.0
  transparent_image: 2.0.0
  flutter_staggered_grid_view: 0.4.1
  flutter_svg: 0.23.0+1
  cached_network_image: 3.1.0+1
  rive: 0.7.33
  any_animated_button: 0.0.2
  auto_animated: 3.0.1

dev_dependencies:
  build_runner: 2.1.2
  flutter_test:
    sdk: flutter
  grinder: 0.9.0
  hive_generator: 1.1.1
  json_serializable: 5.0.2
  flutter_launcher_icons: 0.9.2
  flutter_native_splash: 1.2.4
  flutter_gen_runner: 4.1.2

flutter_gen:
  integrations:
    flutter_svg: true
    rive: true
    flare_flutter: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/app_icons/prod/
    - assets/app_icons/stag/
    - assets/app_icons/
    - assets/app_icons/dev/
    - assets/
    - assets/images/
    - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
